# by default, the Ghost image will use SQLite (and thus requires no separate database container)
# we have used MySQL here merely for demonstration purposes (especially environment-variable-based configuration)

version: '3.1'
services:
  ghost:
    image: ghost:2.10.1
    restart: always
    ports:
      - 2368:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      url: http://wishstone.in
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ghost
    volumes:
    - './data:/var/lib/mysql'
